server:
  port: 8888

spring:
  datasource:
    username: root
    password: ico9cCQrfKKVi4
    url: jdbc:mysql://host.docker.internal:33306/store?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

SnowFlake:
  workerId: 1
  datacenterId: 1
